export const rows = [
  {
    id: 1,
    firstName: "John gdsfgggggggggggggggggggggggggggggggggggg",
    lastName: "Doe",
    email: "john.doe@example.com",
    age: 28,
    city: "New York",
    country: "USA",
    createdAt: "2024-05-12",
    status: "Active",
    score: 87,
  },
  {
    id: 2,
    firstName: "Sarah",
    lastName: "Williams",
    email: "sarah.williams@example.com",
    age: 31,
    city: "Los Angeles",
    country: "USA",
    createdAt: "2024-04-10",
    status: "Inactive",
    score: 72,
  },
  {
    id: 3,
    firstName: "Michael",
    lastName: "Brown",
    email: "michael.brown@example.com",
    age: 26,
    city: "Chicago",
    country: "USA",
    createdAt: "2024-03-19",
    status: "Active",
    score: 93,
  },
  {
    id: 4,
    firstName: "Emily",
    lastName: "Clark",
    email: "emily.clark@example.com",
    age: 29,
    city: "Houston",
    country: "USA",
    createdAt: "2024-03-22",
    status: "Pending",
    score: 68,
  },
  {
    id: 5,
    firstName: "David",
    lastName: "Martinez",
    email: "david.martinez@example.com",
    age: 35,
    city: "Phoenix",
    country: "USA",
    createdAt: "2024-02-11",
    status: "Active",
    score: 88,
  },
  {
    id: 6,
    firstName: "Olivia",
    lastName: "Harris",
    email: "olivia.harris@example.com",
    age: 30,
    city: "San Diego",
    country: "USA",
    createdAt: "2024-01-29",
    status: "Inactive",
    score: 75,
  },
  {
    id: 7,
    firstName: "James",
    lastName: "Hall",
    email: "james.hall@example.com",
    age: 27,
    city: "Dallas",
    country: "USA",
    createdAt: "2024-04-05",
    status: "Active",
    score: 95,
  },
  {
    id: 8,
    firstName: "Sophia",
    lastName: "Young",
    email: "sophia.young@example.com",
    age: 24,
    city: "San Jose",
    country: "USA",
    createdAt: "2024-04-18",
    status: "Active",
    score: 81,
  },
  {
    id: 9,
    firstName: "Daniel",
    lastName: "Allen",
    email: "daniel.allen@example.com",
    age: 33,
    city: "Austin",
    country: "USA",
    createdAt: "2024-02-14",
    status: "Pending",
    score: 64,
  },
  {
    id: 10,
    firstName: "Ava",
    lastName: "King",
    email: "ava.king@example.com",
    age: 25,
    city: "Seattle",
    country: "USA",
    createdAt: "2024-03-01",
    status: "Active",
    score: 90,
  },
  {
    id: 11,
    firstName: "Ethan",
    lastName: "Scott",
    email: "ethan.scott@example.com",
    age: 29,
    city: "Denver",
    country: "USA",
    createdAt: "2024-01-12",
    status: "Inactive",
    score: 73,
  },
  {
    id: 12,
    firstName: "Mia",
    lastName: "Adams",
    email: "mia.adams@example.com",
    age: 32,
    city: "Portland",
    country: "USA",
    createdAt: "2024-05-22",
    status: "Active",
    score: 89,
  },
  {
    id: 13,
    firstName: "Liam",
    lastName: "Hill",
    email: "liam.hill@example.com",
    age: 34,
    city: "Miami",
    country: "USA",
    createdAt: "2024-02-05",
    status: "Inactive",
    score: 70,
  },
  {
    id: 14,
    firstName: "Isabella",
    lastName: "Baker",
    email: "isabella.baker@example.com",
    age: 23,
    city: "Boston",
    country: "USA",
    createdAt: "2024-03-14",
    status: "Active",
    score: 96,
  },
  {
    id: 15,
    firstName: "Noah",
    lastName: "Nelson",
    email: "noah.nelson@example.com",
    age: 28,
    city: "Atlanta",
    country: "USA",
    createdAt: "2024-04-26",
    status: "Pending",
    score: 67,
  },
  {
    id: 16,
    firstName: "Charlotte",
    lastName: "Carter",
    email: "charlotte.carter@example.com",
    age: 27,
    city: "Orlando",
    country: "USA",
    createdAt: "2024-04-09",
    status: "Active",
    score: 82,
  },
  {
    id: 17,
    firstName: "Benjamin",
    lastName: "Mitchell",
    email: "benjamin.mitchell@example.com",
    age: 36,
    city: "Las Vegas",
    country: "USA",
    createdAt: "2024-05-01",
    status: "Inactive",
    score: 71,
  },
  {
    id: 18,
    firstName: "Amelia",
    lastName: "Perez",
    email: "amelia.perez@example.com",
    age: 26,
    city: "Detroit",
    country: "USA",
    createdAt: "2024-03-09",
    status: "Active",
    score: 92,
  },
  {
    id: 19,
    firstName: "Lucas",
    lastName: "Roberts",
    email: "lucas.roberts@example.com",
    age: 31,
    city: "Charlotte",
    country: "USA",
    createdAt: "2024-02-22",
    status: "Pending",
    score: 66,
  },
  {
    id: 20,
    firstName: "Harper",
    lastName: "Turner",
    email: "harper.turner@example.com",
    age: 29,
    city: "San Francisco",
    country: "USA",
    createdAt: "2024-01-18",
    status: "Active",
    score: 94,
  },
];
